export enum Types {
    Bug = 'bug',
    Dark = 'dark',
    Dragon = 'dragon',
    Electric = 'electric',
    Fairy = 'fairy',
    Fighting = 'fighting',
    Fire = 'fire',
    Flying = 'flying',
    Ghost = 'Ghost',
    Grass = 'grass',
    Ground = 'ground',
    Ice = 'ice',
    Normal = 'normal',
    Poison = 'poison',
    Psychic = 'psychic',
    Rock = 'rock',
    Steel = 'steel',
    Water = 'water'
}